server:
  port: 8083
  
spring:
  application:
    name: springCloud-web

eureka:
  instance:
    prefer-ip-address: true #访问的路径变为 IP 地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #使得服务实例在eureka界面增加显示版本号
    lease-renewal-interval-in-seconds: 5  #心跳
    lease-expiration-duration-in-seconds: 15
  client:
    register-with-eureka: true # 是否作为一个Eureka Client 注册到Eureka Server上去
    fetch-registry: true # 是否需要从Eureka Server上拉取注册信息到本地(决定Eureka服务端集群是否自动同步)。
    service-url:
      defaultZone: http://root:123456@127.0.0.1:8091/eureka/

feign:
  hystrix:
    enabled: true
    
ribbon:
  ConnectTimeout: 2000 # 设置连接超时时间
  ReadTimeout: 5000 # 设置读取超时时间
  ServerListRefreshInterval: 2000 # 调整刷新server list的时间间隔
  MaxAutoRetries: 1 # 对当前实例的重试次数
  MaxAutoRetriesNextServer: 2 # 切换实例的重试次数
  
hystrix:
  command: 
    default: #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #断路器超时时间，默认1000ms
