#服务端口配置
server: 
  port: 8091
  
#服务安全配置
spring:
  application:
    name: eureka-server2
  security:
    user:
      name: root
      password: 123456

#Eureka 配置
eureka:
  instance: #Eureak实例定义
    prefer-ip-address: false #访问的路径变为 IP 地址
    hostname: eureka-server2 #定义Eureka 实例所在的主机名称
    lease-renewal-interval-in-seconds: 3 #心跳间隔时间
    lease-expiration-duration-in-seconds: 7 #服务失效时间： 如果多久没有收到请求，则可以删除服务
  server:
    enable-self-preservation: false #是否开启保护模式
    # Eureka Server 自我保护系数：当enable-self-preservation=true时，启作用
    # renewal-percent-threshold:
    eviction-interval-timer-in-ms: 3000
    peer-eureka-nodes-update-interval-ms: 6000 # 集群之间相互更新节点信息的时间频率
    use-read-only-response-cache: true #是否开启缓存
    renewal-percent-threshold: 0.49
  client: #客户端进行Eureka注册的配置
    register-with-eureka: true #是否向注册中心注册自己，集群为true
    fetch-registry: true #是否从注册中心获取注册信息，集群为true
    eureka-service-url-poll-interval-seconds: 60 # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    service-url: #Eureka服务地址
      defaultZone: http://root:123456@192.168.0.108:8092/eureka/ #客户端注册地址
      #server:  #配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
        #enable-self-preservation: false #关闭注册中心的保护机制，Eureka 会统计15分钟之内心跳失败的比例低于85%将会触发保护机制，不剔除服务提供者，如果关闭服务注册中心将不可用的实例正确剔除
        #eviction-interval-timer-in-ms: 5000 #清理间隔
    